# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase Hosting on Push

# Controls when the action will run. 
# This triggers the workflow on push events but only for the main branch
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # This step is not always needed, but good to have if you have a build process
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          channelId: live
          projectId: docuease-y40m1 # <-- IMPORTANT: Make sure this is your project ID